language: node_js
node_js:
  - node

install:
  - npm install

script: 
  - npm run test:unit
  - npm run build

# jobs:
#   include:
#     - stage: test
#       script: npm run test:unit
#     - stage: build
#       script: npm run build