language: node_js
node_js:
  - node

install:
  - npm install

script: 
  - npm run test:unit
  - npm run build

deploy:
  provider: s3
  access_key_id: $AccesskeyID
  secret_access_key: $SecretAccesskey
  bucket: "cicdpractice"
  skip_cleanup: true
  region: "ap-northeast-1"
  local_dir: dist
